---
title: "SPSS | Blank Output"
author: "Craig A. Wendorf"
site: bookdown::bookdown_site
output: bookdown::bs4_book
url: https://cwendorf.github.io/Sourcebook
description: This page provides blank output for SPSS.
---

# SPSS | Blank Output

## Frequencies (Frequencies and Descriptives)

### Frequencies

Variable: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

|||Frequency|Percent|Valid Percent|Cumulative Percent|
| :- | :- | :-: | :-: | :-: | :-: |
|Valid|\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |Total|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_| |

### Statistics

Variable:\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

|Statistic|||
| :- | :-: | :-: |
|N|Valid|\_\_\_\_\_\_\_\_\_\_|
|Mean||\_\_\_\_\_\_\_\_\_\_|
|Std. Deviation||\_\_\_\_\_\_\_\_\_\_|
|Variance||\_\_\_\_\_\_\_\_\_\_|
|Percentiles|25|\_\_\_\_\_\_\_\_\_\_|
| |50|\_\_\_\_\_\_\_\_\_\_|
| |75|\_\_\_\_\_\_\_\_\_\_|

## Correlations (Bivariate)

### Descriptive Statistics

| |Mean|Std. Deviation|N|
| :- | :-: | :-: | :-: |
|Variable: \_\_\_\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|Variable: \_\_\_\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

### Correlations

| | |Variable:<br>\_\_\_\_\_\_\_\_\_|Variable:<br>\_\_\_\_\_\_\_\_\_|
| :- | :- | :-: | :-: |
|Variable:<br>\_\_\_\_\_\_\_\_\_    |Pearson Correlation|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
||Sig. (2-tailed)| |XXXXX|
||Sum of Squares and Cross-products|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
||Covariance|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
||N|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|Variable:<br>\_\_\_\_\_\_\_\_\_    |Pearson Correlation|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
||Sig. (2-tailed)|XXXXX| |
||Sum of Squares and Cross-products|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
||Covariance|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
||N|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

## Explore (Descriptives and Confidence Intervals)

### Case Processing Summary

||Valid||Missing||Total||
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
||**N**|**Percent**|**N**|**Percent**|**N**|**Percent**|
|Variable: \_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_|

### Descriptives

||||Statistic|Std. Error|
| :- | :- |:- | :-: | :-: |
|Variable: \_\_\_\_\_\_\_\_\_|Mean||\_\_\_\_\_|\_\_\_\_\_|
||95% Confidence Interval for the Mean|Lower Bound|\_\_\_\_\_||
|||Upper Bound|\_\_\_\_\_||
||5% Trimmed Mean||\_\_\_\_\_||
||Median||\_\_\_\_\_||
||Variance||\_\_\_\_\_||
||Std. Deviation||\_\_\_\_\_||
||Minimum||\_\_\_\_\_||
||Maximum||\_\_\_\_\_||
||Range||\_\_\_\_\_||
||Interquartile Range||\_\_\_\_\_||
||Skewness||\_\_\_\_\_|\_\_\_\_\_|
||Kurtosis||\_\_\_\_\_|\_\_\_\_\_|

## T Test (One Sample)

### One-Sample Statistics

||N|Mean|Std. Deviation|Std. Error Mean|
| :- | :-: | :-: | :-: | :-: |
|Variable: \_\_\_\_\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

### One-Sample Test

Test Value = \_\_\_\_\_\_\_

| |||||95% Confidence Interval <br>of the Difference||
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
| |**t**|**df**|**Sig. (2-tailed)**|**Mean Difference**|**Lower**|**Upper**|
|Variable: \_\_\_\_\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|

## T-Test (Paired Samples)

### Paired Samples Statistics

|||Mean|N|Std. Deviation|Std. Error Mean|
| :- | :- | :-: | :-: | :-: | :-: | 
|Pair 1|Variable 1:<br>\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
||Variable 2:<br>\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### Paired Samples Correlations

|||N|Correlation|Sig.|
| :- |:- |:-: |:-: |:-: |
|Pair 1|Variable 1 & Variable 2|\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_|

### Paired Samples Test

||||||95% Confidence Interval <br>of the Difference|||||
| :- | :- | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
|||**Mean**|**Std. Dev.**|**Std. Error Mean**|**Lower**|**Upper**|**t**|**df**|**Sig. (2-tailed)**|
|Pair 1|Variable 1 & Variable 2|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_\_|

## T-Test (Independent Samples)

### Group Statistics

| |Group|N|Mean|Std. Deviation|Std. Error Mean|
| :- | :- | :-: | :-: | :-: | :-: |
|Variable: \_\_\_\_\_\_\_\_\_|Level 1|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |Level 2|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

### Independent Samples Test

| | ||||||95% Confidence Interval <br>of the Difference||
| :- | :- | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| | |**t**|**df**|**Sig. (2-tailed)**|**Mean Difference**|**Std. Error Difference**|**Lower**|**Upper**|
|Variable: \_\_\_\_\_\_\_\_\_|Equal variances assumed|\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|
| |Equal variances not assumed|XXXX|XXX|XXXX|XXXXX|XXXXXX|XXXXX|XXXXX|

## Oneway (OneWay ANOVA)

### Descriptives

||||||95% Confidence Interval <br>for Mean||
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
| |**N**|**Mean**|**Std. Deviation**|**Std. Error**|**Lower Bound**|**Upper Bound**|
|Level 1|\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 2|\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 3|\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Total|\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### ANOVA

||Sum of Squares|df|Mean Square|F|Sig.|
| :- | :-: | :-: | :-: | :-: | :-: |
|Between Groups|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Within Groups|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|||
|Total|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_||||

## General Linear Model (Repeated Measures ANOVA)

### Tests of Between-Subjects Effects

|Source|Type III Sum of Squares|df|Mean Square|F|Sig.|
| :- | :-: | :-: | :-: | :-: | :-: |
|Intercept|XXXXXX|XXXX|XXXXXX|XXXXX|XXXXX|
|Error|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_| | |

### Tests of Within-Subjects Effects

|Source| |Type III Sum of Squares|df|Mean Square|F|Sig.|
| :- | :- | :-: | :-: | :-: | :-: | :-: |
|Treatment|Sphericity Assumed|\_\_\_\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
| |Greenhouse-Geisser|XXXXXX|XXXX|XXXXXX|XXXXX|XXXXX|
| |Huynh-Feldt|XXXXXX|XXXX|XXXXXX|XXXXX|XXXXX|
| |Lower-bound|XXXXXX|XXXX|XXXXXX|XXXXX|XXXXX|
|Error|Sphericity Assumed|\_\_\_\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_\_\_|||
| |Greenhouse-Geisser|XXXXXX|XXXX|XXXXXX| | |
| |Huynh-Feldt|XXXXXX|XXXX|XXXXXX| | |
| |Lower-bound|XXXXXX|XXXX|XXXXXX| | |

## Univariate Analysis of Variance (Factorial ANOVA)

### Tests of Between-Subjects Effects

Dependent Variable: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

|Source|Type III Sum of Squares|df|Mean Square|F|Sig.|Partial Eta Squared|
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
|Corrected Model|XXXXXXX|XXXXX|XXXXXXX|XXXXXXX|XXXX|XXXX|
|Intercept|XXXXXXX|XXXXX|XXXXXXX|XXXXXXX|XXXX|XXXX|
|Factor A|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|
|Factor B|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|
|Factor A \* Factor B|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|
|Error|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_||||
|Total|XXXXXXX|XXXXX|||||
|Corrected Total|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_|||||
