---
title: "Statistics for Social Science"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Standardized Scores}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

## Standardized Scores

### Enter Data

```{r}
Outcome <- c(0,0,3,5,4,7,4,9)
StandardizedData <- data.frame(Outcome)
StandardizedData
```

### Calculate Frequencies

```{r}
FrequencyTable <- table(Outcome)
FrequencyTable
prop.table(FrequencyTable)
barplot(FrequencyTable)

mean(Outcome)
var(Outcome)
sd(Outcome)
```

### Calculate Standardized Scores

```{r}
zScores <- scale(Outcome)
StandardizedData <- data.frame(Outcome,zScores)
StandardizedData

zFrequencyTable <- table(Outcome)
zFrequencyTable
prop.table(zFrequencyTable)
barplot(zFrequencyTable)

mean(zScores)
var(zScores)
sd(zScores)
```
