---
title: "jamovi | Blank Output"
author: "Craig A. Wendorf"
site: bookdown::bookdown_site
output: bookdown::bs4_book
url: https://cwendorf.github.io/Sourcebook
description: This page provides blank output for jamovi.
---

# jamovi | Blank Output

## ANOVA (Factorial ANOVA)

### Descriptives

Variable: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ 

|Factor A|Factor B|Mean|SD|N|
| :- | :- | :-: | :-: | :-: |
|Level 1|Level 1|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
||Level 2|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 2|Level 1|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
||Level 2|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### ANOVA

Variable: \_\_\_\_\_\_\_\_\_\_\_

||Sum of Squares|df|Mean Square|F|p|η<sup>2</sup>|
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
|Factor A|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Factor B|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Factor A \* Factor B|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Residual|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_||||

*Note.* Type III Sum of Squares

## Correlations (Bivariate)

### Descriptives

| |Variable:<br>\_\_\_\_\_\_\_\_\_|Variable:<br>\_\_\_\_\_\_\_\_\_|
| :- | :-: | :-: |
|N|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_|
|Missing|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_|
|Mean|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Std. Deviation|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### Correlation Matrix

| | |Variable:<br>\_\_\_\_\_\_\_\_\_|Variable:<br>\_\_\_\_\_\_\_\_\_|
| :- | :- | :-: | :-: |
|Variable:<br>\_\_\_\_\_\_\_\_\_|Pearson’s r|XXXXX|\_\_\_\_\_\_\_|
||p-value|XXXXX|\_\_\_\_\_\_\_|
|Variable:<br>\_\_\_\_\_\_\_\_\_|Pearson’s r||XXXXX|
||p-value||XXXXX|

## T-Test (Confidence Intervals)

### Descriptives

|Variable:|N|Mean|Median|SD|SE|
| :- | :-: | :-: | :-: | :-: | :-: |
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

### One-Sample T-Test

||||||95% Confidence Interval||
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
|**Variable:**|**Statistic**|**df**|**p**|**Mean Difference**|**Lower**|**Upper**|
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|

## T-Test (One Sample)

### Descriptives

|Variable:|N|Mean|Median|SD|SE|
| :- | :-: | :-: | :-: | :-: | :-: |
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

### One-Sample T-Test

||||||95% Confidence Interval|||
| :- | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
|**Variable:**|**Statistic**|**df**|**p**|**Mean Difference**|**Lower**|**Upper**|**Cohen’s d**|
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|

*Note.* All tests, hypothesis is population mean is different from \_\_\_\_\_\_

## T-Test (Paired Samples)

### Descriptives

|Variable:|N|Mean|Median|SD|SE|
| :- | :-: | :-: | :-: | :-: | :-: |
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

### Paired Samples T-Test

| ||||||95% Confidence Interval||
| :- | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
|**Variables:**|**Statistic**|**df**|**p**|**Mean Difference**|**SE Difference**|**Lower**|**Upper**|**Cohen’s d**|
|\_\_\_\_\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|

## T-Test (Independent Samples)

### Group Descriptives

|Variable:|Group|N|Mean|Median|SD|SE|
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
||\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

### Independent Samples T-Test

| ||||||95% Confidence Interval||
| :- | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
|**Variables:**|**Statistic**|**df**|**p**|**Mean Difference**|**SE Difference**|**Lower**|**Upper**|**Cohen’s d**|
|\_\_\_\_\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|

## ANOVA (OneWay ANOVA)

### Descriptives

|Factor: \_\_\_\_\_\_\_\_\_|N|Mean|SD|
| :- | :-: | :-: | :-: |
|Level 1|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 2|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 3|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### ANOVA

||Sum of Squares|df|Mean Square|F|p|η<sup>2</sup>|
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
|Factor: \_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Residuals|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_||||

## Post Hoc Comparisons (OneWay ANOVA)

### Descriptives

|Factor: \_\_\_\_\_\_\_\_\_|N|Mean|SD|
| :- | :-: | :-: | :-: |
|Level 1|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 2|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 3|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### Post Hoc Comparisons

Variable: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ 

|Factor: \_\_\_\_\_\_|Factor: \_\_\_\_\_\_|Mean Difference|SE|df|t|p<sub>TUKEY</sub>|
| :- | :- | :-: | :-: | :-: | :-: | :-: |
|Level 1|Level 2|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
||Level 3|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|Level 2|Level 3|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

## Repeated Measures ANOVA

### Descriptives

|Factor: \_\_\_\_\_\_\_\_\_|N|Mean|SD|
| :- | :-: | :-: | :-: |
|Level 1|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 2|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 3|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### Within Subjects Effects

||Sum of Squares|df|Mean Square|F|p|Partial η<sup>2</sup>|
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
|RM Factor 1|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Residual|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_||||

*Note.* Type 3 Sum of Squares

### Between Subjects Effects

||Sum of Squares|df|Mean Square|F|p|Partial η<sup>2</sup>|
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
|Residual|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_||||

*Note.* Type 3 Sum of Squares

## ANOVA (Factorial ANOVA)

### Descriptives

|Factor A|Factor B|N|Mean|SD|
| :-: | :-: | :-: | :-: | :-: |
|Level 1|Level 1|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 1|Level 2|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 2|Level 1|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 2|Level 2|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### ANOVA

||Sum of Squares|df|Mean Square|F|p|η<sup>2</sup>|
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
|Factor A|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Factor B|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Factor A \* Factor B|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Residual|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_||||
