---
title: "Sourcebook"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Confidence Intervals}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

# R | Data Analysis

## Confidence Intervals

### Entering Data

Enter the data in a vector that assigns a variable name.

```{r}
Outcome <- c(0,0,3,5,4,7,4,9)
```

### Viewing Data

Create and display a data frame to view the data set.

```{r}
IntervalsData <- data.frame(Outcome)
IntervalsData
```

### Obtaining Descriptive Statistics

Get the mean and standard deviation for the variable.

```{r}
mean(Outcome)
sd(Outcome)
```

### Obtaining Inferential Statistics

Get the mean and its confidence interval.

```{r}
t.test(Outcome)$conf.int
t.test(Outcome,conf.level=.99)$conf.int
```
