---
title: "JASP | Blank Output"
author: "Craig A. Wendorf"
site: bookdown::bookdown_site
output: bookdown::bs4_book
url: https://cwendorf.github.io/Sourcebook
description: This page provides blank output for JASP.
---

# JASP | Blank Output

## Descriptives (Frequencies and Descriptives)

### Frequencies

Frequencies for \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

||Frequency|Percent|Valid Percent|Cumulative Percent|
| :- | :-: | :-: | :-: | :-: |
|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|Total|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_| |

### Descriptive Statistics

|Variable:|\_\_\_\_\_\_\_\_\_\_|
| :- | :-: |
|Valid|\_\_\_\_\_\_\_\_\_\_|
|Missing|\_\_\_\_\_\_\_\_\_\_|
|Mean|\_\_\_\_\_\_\_\_\_\_|
|Std. Deviation|\_\_\_\_\_\_\_\_\_\_|
|Variance|\_\_\_\_\_\_\_\_\_\_|
|25th percentile|\_\_\_\_\_\_\_\_\_\_|
|50th percentile|\_\_\_\_\_\_\_\_\_\_|
|75th percentile|\_\_\_\_\_\_\_\_\_\_|

## Correlations (Bivariate)

### Descriptives

Descriptive Statistics

| |Variable:<br>\_\_\_\_\_\_\_\_\_|Variable:<br>\_\_\_\_\_\_\_\_\_|
| :- | :-: | :-: |
|Valid|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_|
|Missing|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_|
|Mean|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Std. Deviation|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### Descriptives

Pearson Correlations	

| | |Variable:<br>\_\_\_\_\_\_\_\_\_|Variable:<br>\_\_\_\_\_\_\_\_\_|
| :- | :- | :-: | :-: |
|Variable:<br>\_\_\_\_\_\_\_\_\_|Pearson’s r|XXXXX|\_\_\_\_\_\_\_|
||p-value|XXXXX|\_\_\_\_\_\_\_|
|Variable:<br>\_\_\_\_\_\_\_\_\_|Pearson’s r||XXXXX|
||p-value||XXXXX|

## T-Test (Confidence Intervals)

### Descriptives

|Variable:|N|Mean|SD|SE|
| :- | :-: | :-: | :-: | :-: |
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

### One-Sample T-Test

| ||||95% Confidence Interval||
| :- | :-: | :-: | :-: | :-: | :-: |
|**Variable:**|**t**|**df**|**p**|**Lower**|**Upper**|
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|

## T-Test (One Sample)

### Descriptives

|Variable:|N|Mean|SD|SE|
| :- | :-: | :-: | :-: | :-: |
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

### One-Sample T-Test

||||||95% Confidence Interval|||
| :- | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
|**Variable:**|**t**|**df**|**p**|**Mean Difference**|**Lower**|**Upper**|**Cohen’s d**|
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|

*Note.* For all tests, the alternative hypothesis specifies that the population mean is different from \_\_\_\_\_\_

## T-Test (Paired Samples)

### Descriptives

|Variable:|N|Mean|SD|SE|
| :- | :-: | :-: | :-: | :-: |
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

### Paired Samples T-Test

||||||95% Confidence Interval|||
| :- | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
|**Variables:**|**t**|**df**|**p**|**Mean Difference**|**Lower**|**Upper**|**Cohen’s d**|
|\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|

## T-Test (Independent Samples)

### Group Descriptives

|Variable:|Group|N|Mean|SD|SE|
| :- | :-: | :-: | :-: | :-: | :-: |
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|
||\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_|

### Independent Samples T-Test

||||||95% Confidence Interval|||
| :- | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
|**Variable:**|**t**|**df**|**p**|**Mean Difference**|**Lower**|**Upper**|**Cohen’s d**|
|\_\_\_\_\_|\_\_\_\_\_|\_\_\_\_|\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|\_\_\_\_\_\_|

*Note.* All tests, variances of groups assumed equal

## ANOVA (OneWay ANOVA)

### Descriptives

Variable: \_\_\_\_\_\_\_\_\_\_\_

|Factor: \_\_\_\_\_\_\_\_\_|Mean|SD|N|
| :- | :-: | :-: | :-: |
|Level 1|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 2|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 3|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### ANOVA

Variable: \_\_\_\_\_\_\_\_\_\_\_

||Sum of Squares|df|Mean Square|F|p|η<sup>2</sup>|
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
|Factor: \_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Residual|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_||||

*Note.* Type III Sum of Squares

## Repeated Measures ANOVA

### Descriptives 

|RM Factor 1|Mean|SD|N|
| :- | :-: | :-: | :-: |
|Level 1|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 2|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### Within Subjects ANOVA

||Sum of Squares|df|Mean Square|F|p|η<sup>2</sup>|
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
|RM Factor 1|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Residual|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_||||

*Note.* Type III Sum of Squares

## ANOVA (Factorial ANOVA)

### Descriptives

Variable: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ 

|Factor A|Factor B|Mean|SD|N|
| :- | :- | :-: | :-: | :-: |
|Level 1|Level 1|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
||Level 2|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Level 2|Level 1|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
||Level 2|\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|

### ANOVA

Variable: \_\_\_\_\_\_\_\_\_\_\_

||Sum of Squares|df|Mean Square|F|p|η<sup>2</sup>|
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
|Factor A|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Factor B|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Factor A \* Factor B|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|
|Residual|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_|\_\_\_\_\_\_\_\_\_\_||||

*Note.* Type III Sum of Squares
